name: TEST CI

on:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm run build
          ls
          sudo chown -R $USER dist
          sudo chmod -R 777 dist
          cd dist
          pwd

      - name: Docschina Github Action
        id: docschinaDeploy
        uses: docschina/docschina-actions@master
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          staticSrcPath: dist
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}
          isForce: ${{ secrets.ISFORCE }}
          envId: ${{ secrets.ENV_ID }}

      - name: Get Deployment Result
        run: echo "Deploy to docschina result ${{ steps.docschinaDeploy.outputs.deployResult }}"
