name: TEST CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Docschina Github Action
        id: docschinaDeploy
        uses: lcxfs1991/docschina-actions@master
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          staticSrcPath: ./build
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}
          isForce: ${{ secrets.ISFORCE }}

      - name: Get Deployment Result
        run: echo "Deploy to docschina result ${{ steps.docschinaDeploy.outputs.deployResult }}"

